Interactive list
elmar8287/todo-list pull request #2
Opened 2021-07-29 15:33 UTC by elmar8287

- Add drag and drop functionality
- Add delete button for each task

2021-07-29 16:02 UTC, mimipeshy requested changes
## Hi @elmar8287  👋🏾 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
#### Highlights

- items render dynamically on page load ✔️ 
- i can drag items easily ✔️ 
- good GitHub workflow ✔️ 
- not forming any linter errors ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

2021-07-29 16:02 UTC, mimipeshy commented on src/index.js
>  // }
- [x] Kindly remove all commented out code to keep your code base clean

2021-07-29 16:02 UTC, mimipeshy commented on src/index.js
> +// };
- [x] Kindly remove commented out code to keep your codebase clean

2021-07-29 16:02 UTC, mimipeshy commented on src/index.js
> +  }).element
- [ ] From the project specifications listed [here](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m2_interactive_list.md), you were supposed to create two different files  ⬇️ 
![image](https://user-images.githubusercontent.com/33067256/127524522-530435f9-ab3c-4d21-a387-db4549418d85.png)

- [ ] When i drag an item to another index, it should update the items index as stated here ⬇️ 
![image](https://user-images.githubusercontent.com/33067256/127525051-5f8ac7de-c0f7-43de-9df9-c679dc55e643.png)
```
Example
I have three todo's with different indexes, A,B,C. If i move C to replace B, C's new index should be B's previous index. 
```
Hope that is clear enough

- [ ] When i click on completed on a task, it should change from `false` to `true` and vice versa


- [ ] From the Learning Objectives listed [here](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m2_interactive_list.md) the last point states that you should use ES6 modules to write modular js. This means using `arrow functions` over the `function` keywork. Kindly fix this also

2021-07-31 17:42 UTC, de-scholar approved these changes
Hi @elmar8287 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- [ ] I would still suggest you remove [these commented codes](https://github.com/elmar8287/todo-list/blob/a3fada0cb9382dc0988be853f0af03fde55939b4/src/index.js#L164-L166)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-31 17:49 UTC, ZawadiSumba66 requested changes
#### Hi @elmar8287, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 

You have submitted the interactive list project for the add_remove task project. Could it be because you submitted the project with the wrong link on your dashboard? Please rectify this and request another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-07-31 18:01 UTC, merged

2021-08-31 15:49 UTC, elmar8287 commented
Dear @de-scholar! 🥇 

Many thanks for the review. I appreciate your comments 👍 

Many thanks and regards,

Elmar

2021-08-31 15:50 UTC, elmar8287 commented
Dear @ZawadiSumba66! 🥇 

Sorry for the missunderstanding. 

Many thanks and regards,

Elmar